### ISSUE TITLE
Add Shipments endpoint - no Model currently

### ISSUE THREAD

**Issue by billda** [zack6849/ship-station#7]
Tried to use this library to pull Shipments, and it's not working - looks like there is no Model defined for Shipments, even though there is limited mention of Shipments elsewhere in the library. 

Perhaps it's causing the 500 error I'm getting when trying to retrieve Shipments?

**Comment by billda** [comment]
Here is my code:
```
$ss = new ShipStationApi($ss_api_key, $ss_api_secret, $ss_options);

$shipments = $ss->Shipments->listShipments('createDateStart='.date('Y-m-d')."&createDateEnd=".date('Y-m-d')."includeShipmentItems=true&pageSize=100");
```

And here is the error:
```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 22: The requested URL returned error: 500 Internal Server Error (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Users/bill/Dropbox (Personal)/dev/wh-scoreboard/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:201
Stack trace:
#0 /Users/bill/Dropbox (Personal)/dev/wh-scoreboard/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /Users/bill/Dropbox (Personal)/dev/wh-scoreboard/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /Users/bill/Dropbox (Personal)/dev/wh-scoreboard/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHt in /Users/bill/Dropbox (Personal)/dev/wh-scoreboard/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 201
```

**Comment by billda** [comment]
I think I identified the problem - the library does not properly handle requests to the root of any endpoint if there are parameters. Here's the exact URL throwing the error:

```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `GET https://ssapi.shipstation.com/shipments/?createDateStart=2020-07-27&createDateEnd=2020-07-27includeShipmentItems=true&pageSize=100` resulted in a `500 Internal Server Error` response:
```
